### ISSUE TITLE
Startup fails when target directory does not exist

### ISSUE THREAD

**Issue by kaklakariada** [exasol/exasol-test-setup-abstraction-java#46]
Startup fails when `target` directory does not exist.

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
        at com.exasol.containers.ExasolContainer.start(ExasolContainer.java:509)
        at com.exasol.exasoltestsetup.testcontainers.ExasolTestcontainerTestSetup.<init>(ExasolTestcontainerTestSetup.java:34)
        at com.exasol.exasoltestsetup.ExasolTestSetupFactory.getTestSetup(ExasolTestSetupFactory.java:48)
        at com.exasol.testsetupabstraction.server.Main.main(Main.java:37)
Caused by: com.exasol.containers.ExasolContainerInitializationException: Could not create SSH key pair
        at com.exasol.containers.ExasolContainer.getSshKeys(ExasolContainer.java:999)
        at com.exasol.containers.ExasolContainer.createDockerAccess(ExasolContainer.java:985)
        at com.exasol.containers.ExasolContainer.configure(ExasolContainer.java:186)
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:327)
        ... 5 more
Caused by: java.nio.file.NoSuchFileException: target/id_rsa
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
        at com.exasol.containers.ssh.SshKeys$Builder.writeToFiles(SshKeys.java:121)
        at com.exasol.containers.ssh.SshKeys$Builder.createKeyPair(SshKeys.java:111)
        at com.exasol.containers.ssh.SshKeys$Builder.build(SshKeys.java:104)
        at com.exasol.containers.ExasolContainer.getSshKeys(ExasolContainer.java:997)
        ... 8 more
```

**Comment by ckunki** [comment]
Hello @kaklakariada : 
https://github.com/exasol/exasol-testcontainers/issues/206 is closed now. AFAIK the logic described in the current ticket should be implemented in ETC 206. 
Can the current ticket simply be rephrased to just update dependency to ETC?
