### ISSUE TITLE
SSH connection fails for Exasol Docker-DB 8.26.0

### ISSUE THREAD

**Issue by kaklakariada** [exasol/exasol-test-setup-abstraction-java#82]
Starting a local docker-db 8.26.0 fails with the following error message (see [this build](https://github.com/exasol/cloud-storage-extension/actions/runs/9098215431/job/25007896858?pr=317)):
```
java.lang.IllegalStateException: 
E-ETAJ-12: Failed to ssh to the exasol database. This is required for redirecting a host port. Known mitigations:
* Make sure the database is reachable, i.e. port 32788 open on host 'localhost'.
* Make sure user 'root' can login to the database using your ssh-key.
	at com.exasol.exasoltestsetup.SshConnection.createSession(SshConnection.java:53)
	at com.exasol.exasoltestsetup.SshConnection.<init>(SshConnection.java:31)
	at com.exasol.exasoltestsetup.testcontainers.ExasolTestcontainerTestSetup.<init>(ExasolTestcontainerTestSetup.java:38)
	at com.exasol.exasoltestsetup.ExasolTestSetupFactory.getTestSetup(ExasolTestSetupFactory.java:123)
	at com.exasol.cloudetl.extension.ExtensionIT.setup(ExtensionIT.java:49)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: com.jcraft.jsch.JSchException: Algorithm negotiation fail
	at com.jcraft.jsch.Session.receive_kexinit(Session.java:590)
	at com.jcraft.jsch.Session.connect(Session.java:320)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.exasol.exasoltestsetup.SshConnection.createSession(SshConnection.java:39)
	... 6 more
```

Docker-DB 8.25.0 works fine.

**Comment by kaklakariada** [comment]
## Background
SSH connection to the container is used for forwarding ports from/to the Exasol DB.
* Ports are not known at container start but added dynamically
* TestContainers allows adding custom exposed ports with `container.withExposedPorts(...)`, but this takes effect only **before** container start. Adding ports after start has no effect.
  * See methods `GenericContainer.applyConfiguration()` and `ContainerDef.applyTo()`
